# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='apadah',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
